name: 'SSH Rsync CI/CD Action'
description: 'CI/CD for deploying assets to server via rsync'
author: bshelling@gmail.com
branding:
  icon: 'server'
  color: 'orange'
inputs:
  privkey:
    description: "Server key"
    required: true
  host:
    description: "Host"
    required: true
  username:
    description: "Username"
    required: true
  hostname:
    description: "Host"
    required: true
  options:
    description: "Command Options"
    required: true
  serverpath:
    description: "Server Path"
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.privkey }}
    - ${{ inputs.host }}
    - ${{ inputs.username }}
    - ${{ inputs.hostname }}
    - ${{ inputs.serverpath }}